# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    # Specify labels for npm pull requests
    labels:
      - 'npm'
      - 'dependencies'
    versioning-strategy: increase

  # Enable version updates for Docker
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'daily'
    labels:
      - 'rust'
      - 'dependencies'
